spring:
  profiles:
    active: dev
  application:
    name: v1

## Jackson binding config
  jackson:
    serialization:
      fail-on-empty-beans: false
    
## File Storage Properties
file:
  upload-dir: ./uploads